language: cpp
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update
 - sudo apt-cache search arm
 - wget https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz --no-check-certificate
 - tar -xzf cmake-3.4.1.tar.gz
 - (cd cmake-3.4.1 && mkdir build)
 - (cd cmake-3.4.1/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr)
 - (cd cmake-3.4.1/build && sudo make install)
 - (cd cmake-3.4.1/build && sudo ldconfig)
 - sudo apt-get install -y gcc-arm-none-eabi
 - git submodule update --init --recursive
script:
 - make
env:
os:
- linux