language: cpp
compiler: 
  - gcc
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq "g++-4.8"
 - export CXX="g++-4.8" CC="gcc-4.8"
 - sudo apt-get install -y gcc-arm-none-eabi
 - wget http://www.atmel.com/images/avr8-gnu-toolchain-3.4.5.1522-linux.any.x86.tar.gz -O avr8.tar.gz
 - tar -zxf avr8.tar.gz
 - export PATH="$PATH:$TRAVIS_BUILD_DIR/avr8-gnu-toolchain-linux_x86/bin"
 - wget https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz --no-check-certificate
 - tar -xzf cmake-3.4.1.tar.gz
 - (cd cmake-3.4.1 && mkdir build)
 - (cd cmake-3.4.1/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr)
 - (cd cmake-3.4.1/build && sudo make install)
 - (cd cmake-3.4.1/build && sudo ldconfig)
script:
 - git submodule update --init --recursive
 - make
env:
os:
- linux
