cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_TARGET "native" CACHE STRING "")
set(AVERSIVE_PLATFORM    native)
set(AVERSIVE_MCU         native)

include("${CMAKE_CURRENT_LIST_DIR}/simul.cmake")

set(AVERSIVE_TOOLCHAIN_NATIVE 1 CACHE STRING "")

set(NATIVE_FLAGS "${NATIVE_FLAGS} -DAVERSIVE_TOOLCHAIN_NATIVE")

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${NATIVE_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${NATIVE_FLAGS}")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${NATIVE_FLAGS}")

set(CMAKE_C_FLAGS   CACHE STRING "")
set(CMAKE_CXX_FLAGS CACHE STRING "")
set(CMAKE_ASM_FLAGS CACHE STRING "")

unset(NATIVE_FLAGS)
