cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_ATMEGA 1 CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/avr.cmake")

set(ATMEGA_FLAGS "-DAVERSIVE_TOOLCHAIN_ATMEGA")

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${ATMEGA_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ATMEGA_FLAGS}")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ATMEGA_FLAGS}")

unset(ATMEGA_FLAGS)
