cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_TARGET "atmega1280")
include("${CMAKE_CURRENT_LIST_DIR}/atmegaxx0_1.cmake")

set(AVERSIVE_TOOLCHAIN_ATMEGA1280 1 CACHE STRING "")

set(ATMEGA1280_FLAGS "-D__AVR_ATmega1280__")
set(ATMEGA1280_FLAGS "${ATMEGA1280_FLAGS} -DAVERSIVE_TOOLCHAIN_ATMEGA1280")

set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} ${ATMEGA1280_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS    "${CMAKE_CXX_FLAGS} ${ATMEGA1280_FLAGS}" CACHE STRING "")
set(CMAKE_ASM_FLAGS    "${CMAKE_ASM_FLAGS} ${ATMEGA1280_FLAGS}" CACHE STRING "")

unset(ATMEGA1280_FLAGS)
