cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_TARGET "atmega32")
include("${CMAKE_CURRENT_LIST_DIR}/atmega.cmake")

set(AVERSIVE_TOOLCHAIN_ATMEGA32 1 CACHE STRING "")

set(ATMEGA32_FLAGS "-D__AVR_ATmega32__")
set(ATMEGA32_FLAGS "${ATMEGA32_FLAGS} -DAVERSIVE_TOOLCHAIN_ATMEGA32")

set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} ${ATMEGA32_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS    "${CMAKE_CXX_FLAGS} ${ATMEGA32_FLAGS}" CACHE STRING "")
set(CMAKE_ASM_FLAGS    "${CMAKE_ASM_FLAGS} ${ATMEGA32_FLAGS}" CACHE STRING "")

unset(ATMEGA32_FLAGS)
