cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_ATMEGAXX0_1 1 CACHE STRING "")

include("${CMAKE_CURRENT_LIST_DIR}/atmega.cmake")

set(ATMEGAXX0_1_FLAGS "-DAVERSIVE_TOOLCHAIN_ATMEGAXX0_1")

set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${ATMEGAXX0_1_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ATMEGAXX0_1_FLAGS}")
set(CMAKE_ASM_FLAGS "${CMAKE_ASM_FLAGS} ${ATMEGAXX0_1_FLAGS}")

unset(ATMEGAXX0_1_FLAGS)
