cmake_minimum_required(VERSION 2.8)
cmake_policy(SET CMP0011 NEW)

set(AVERSIVE_TOOLCHAIN_ATXMEGA192A3 1 CACHE STRING "")

set(AVERSIVE_TOOLCHAIN_TARGET "atxmega192a3")
include("${CMAKE_CURRENT_LIST_DIR}/avr.cmake")

set(ATXMEGA192A3_FLAGS "-D__AVR_ATxmega192A3__")

set(CMAKE_C_FLAGS      "${CMAKE_C_FLAGS} ${ATXMEGA192A3_FLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS    "${CMAKE_CXX_FLAGS} ${ATXMEGA192A3_FLAGS}" CACHE STRING "")
set(CMAKE_ASM_FLAGS    "${CMAKE_ASM_FLAGS} ${ATXMEGA192A3_FLAGS}" CACHE STRING "")

unset(ATXMEGA192A3_FLAGS)
