language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
os: linux
sudo: required
dist: trusty

env:
  - CONAN_COMPILER=gcc CONAN_COMPILER_VERSION=4.8

matrix:
    include:
        - language: generic
          os: osx
          env: PYVER=py27 CONAN_COMPILER=apple-clang CONAN_COMPILER_VERSION=6.0
          
        - language: generic
          os: osx
          env: PYVER=py33 CONAN_COMPILER=apple-clang CONAN_COMPILER_VERSION=6.0
        
        - language: generic
          os: osx
          env: PYVER=py34 CONAN_COMPILER=apple-clang CONAN_COMPILER_VERSION=6.0
          
        - language: generic
          os: osx
          env: PYVER=py35 CONAN_COMPILER=apple-clang CONAN_COMPILER_VERSION=6.0
          
# command to install dependencies
install:
  - ./.ci/travis/install.sh
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export CONAN_LOGGING_LEVEL=10
# command to run tests
script: 
  - ./.ci/travis/run.sh
